#!/usr/bin/env bash

export CONTECO_LABEL="stack.ekg - ContEco"
export CONTECO_DESCRIPTION="EKG Stack image, consisting of ElasticSearch, Grafana and Kibana."

export CONTECO_TYPE="stack"
export CONTECO_NAME="ekg"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
