#!/usr/bin/env bash

export CONTECO_LABEL="Conteco base EKG stack"
export CONTECO_DESCRIPTION="The ContEco base EKG stack."

export CONTECO_TYPE="stack"
export CONTECO_NAME="ekg"
export CONTECO_TAG="v1.0.0"

export CONTECO_BASE="stack.base"
export CONTECO_BUILD="image-base"
