#!/usr/bin/env bash

# CREATING A SERVICE STACK
# 1. Setup initial environment file with the stack services key CONTECO_DC_GLOBAL_SERVICES and empty CONTECO_DC_GLOBAL key
# 2. Run config deploy to regenerate environment and generate environment.template, docker-compose.yml.template and docker-compose.yml 
# 3. Add global configuration keys to CONTECO_DC_GLOBAL and move them up for visibility
# 4. Run config deploy to regenerate all files
# 5. Run deploy to deploy the stack

#!/usr/bin/env bash

# START STACK CONFIGURATION
export CONTECO_DC_GLOBAL_SERVICES='elasticsearch.base,kibana.base,grafana.base'
export CONTECO_DC_GLOBAL='$CONTECO_DC_KIBANA_ELASTICSEARCH_HOSTS'
# END STACK CONFIGURATION

# START GLOBAL SERVICE CONFIGURATION
export CONTECO_DC_KIBANA_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
# END GLOBAL SERVICE CONFIGURATION
