#!/usr/bin/env bash
(
    . executionplane-invoke "$0 $@"
	if [[ $# -gt 1 ]] ; then
		rootPath="${CONTECO_PWD}/${BASH_ARGV[0]}"
	else
		rootPath="${CONTECO_PWD}/$1"
	fi
	if [[ "$1" == "deploy" ]] ; then
		(
		deployPath="$rootPath/conteco/assets/${CONTECO_TYPE}/${CONTECO_NAME}/deploy"
		. $deployPath/environment
		cat $deployPath/docker-compose.yml.template | envsubst "$CONTECO_DC_GLOBAL"\
			> $deployPath/docker-compose.yml
		)
	fi
    executionplane-complete
)
